services:
  organization: 
    build: 
      context: ./backend-services/organization
      dockerfile: Dockerfile
      target: dev
    image: neka-backend-organization
    restart: always
    depends_on:
      - neka-db
    ports:
      - "5001:3000"

  data-access: 
    build: 
      context: ./backend-services/data-access
      dockerfile: Dockerfile
      target: dev
    image: neka-backend-data-access
    restart: always
    depends_on:
      - neka-db
    ports:
      - "5002:3000"
  
  neka-db: 
    image: mysql:5.7.41
    container_name: neka-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thot
      MYSQL_USER: marius
      MYSQL_PASSWORD: root
    ports:
      - "5000:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: