name: CI organization service

on:
  pull_request:
    branches: [main]
    paths:
      - "backend-service/organization/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
