name: CI organization service

on:
  pull_request:
    branches: [main]
    paths:
      - "backend-services/organization/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: actions/setup-docker@v2
        # with:
        #   context: ./backend-services/organization
        #   dockerfile: Dockerfile

      - name: Build Docker image for testing
        run: docker build -t test-image ./backend-services/organization

        # - name: Run tests inside Docker container
        #   run: docker run test-image npm test
